name: Test all the things

on: [ push, pull_request ]

jobs:
  build-agent:
    runs-on: ubuntu-latest
    name: Build agent with Java 8
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Build agent with Java 8
        run: ./gradlew wrapper --gradle-version=7.6.2 :agent:publishToMavenLocal

  ci:
    runs-on: ubuntu-latest
    name: Test with different Java versions
    strategy:
      matrix:
        java: [ 11, 17, 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Test
        run: |
          ./gradlew wrapper --gradle-version=7.6.2 assemble
          ./travis-test.sh